[build]
  command = "cd Public/Frontend && npm install && npm run build"
  publish = "Public/Frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
